from main.views.IndexTemplateView import IndexTemplateView
from main.views.ContatoTemplateView import ContatoTemplateView
from main.views.ContratoTemplateView import ContratoTemplateView
from main.views.EnviarMensagemView import EnviarMensagemView