# Generated by Django 4.2.7 on 2023-11-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_redesocial_delete_redessociais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InicioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Texto principal')),
                ('subtitle', models.TextField(verbose_name='Subtítulo')),
                ('buttonText', models.CharField(max_length=50, verbose_name='Texto do botão')),
                ('buttonLink', models.CharField(max_length=100, verbose_name='Link do botão')),
                ('backgroundImage', models.ImageField(upload_to='inicioBackgrounds/', verbose_name='Imagem de fundo')),
                ('image', models.ImageField(upload_to='inicioImages/', verbose_name='Imagem modelo')),
            ],
            options={
                'verbose_name': 'Seção Início',
            },
        ),
    ]
