# Generated by Django 4.2.7 on 2023-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_iniciosection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iniciosection',
            options={'verbose_name': 'Seção Início', 'verbose_name_plural': 'Seções Início'},
        ),
        migrations.AlterField(
            model_name='iniciosection',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Subtítulo'),
        ),
    ]
