# Generated by Django 4.2.7 on 2023-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_iniciosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPrincipal', models.CharField(max_length=35)),
                ('mensagem', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
            },
        ),
        migrations.AlterModelOptions(
            name='iniciosection',
            options={'verbose_name': 'Seção Início', 'verbose_name_plural': 'Seção Início'},
        ),
    ]
