# Generated by Django 4.2.7 on 2023-11-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contato_alter_iniciosection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostUser', models.CharField(max_length=100, verbose_name='Endereço')),
                ('hostPassword', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Configuração de email',
                'verbose_name_plural': 'Configuração de email',
            },
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.CharField(max_length=200, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tituloPrincipal',
            field=models.CharField(max_length=35, verbose_name='Título Principal'),
        ),
    ]
