# Generated by Django 4.2.7 on 2023-11-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_configuracaoemail_alter_contato_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoEmail',
        ),
    ]
